"""empty message

Revision ID: 0050a77c072d
Revises: 21b28c30e79d
Create Date: 2025-12-27 23:11:46.709296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0050a77c072d"
down_revision: Union[str, Sequence[str], None] = "21b28c30e79d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_list",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("BOOK", "ARTICLE", name="kind_enum", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED", "READING", "DONE", name="status_enum", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW", "NORMAL", "HIGH", name="priority_enum", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=2500), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_list_title"), "reading_list", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_reading_list_user_id"), "reading_list", ["user_id"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_id_name"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "reading_list_tags",
        sa.Column("reading_list_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_list_id"], ["reading_list.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_list_tags_reading_list_id"),
        "reading_list_tags",
        ["reading_list_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_list_tags_tag_id"),
        "reading_list_tags",
        ["tag_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_list_tags_tag_id"), table_name="reading_list_tags")
    op.drop_index(
        op.f("ix_reading_list_tags_reading_list_id"), table_name="reading_list_tags"
    )
    op.drop_table("reading_list_tags")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_reading_list_user_id"), table_name="reading_list")
    op.drop_index(op.f("ix_reading_list_title"), table_name="reading_list")
    op.drop_table("reading_list")
    # ### end Alembic commands ###
