"""empty message

Revision ID: 0847583a3c8f
Revises: e8efd50f9dd7
Create Date: 2026-01-01 22:08:05.151790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0847583a3c8f"
down_revision: Union[str, Sequence[str], None] = "e8efd50f9dd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items", "notes", existing_type=sa.VARCHAR(length=2500), nullable=True
    )
    op.create_index(op.f("ix_items_is_deleted"), "items", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_items_kind"), "items", ["kind"], unique=False)
    op.create_index(op.f("ix_items_priority"), "items", ["priority"], unique=False)
    op.create_index(op.f("ix_items_status"), "items", ["status"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_items_status"), table_name="items")
    op.drop_index(op.f("ix_items_priority"), table_name="items")
    op.drop_index(op.f("ix_items_kind"), table_name="items")
    op.drop_index(op.f("ix_items_is_deleted"), table_name="items")
    op.alter_column(
        "items", "notes", existing_type=sa.VARCHAR(length=2500), nullable=False
    )
    # ### end Alembic commands ###
