"""empty message

Revision ID: e8efd50f9dd7
Revises: 0050a77c072d
Create Date: 2025-12-29 19:15:40.662322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8efd50f9dd7"
down_revision: Union[str, Sequence[str], None] = "0050a77c072d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("BOOK", "ARTICLE", name="item_kind_enum", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "READING",
                "DONE",
                name="item_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "NORMAL",
                "HIGH",
                name="item_priority_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=2500), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_title"), "items", ["title"], unique=False)
    op.create_index(op.f("ix_items_user_id"), "items", ["user_id"], unique=False)
    op.create_table(
        "item_tags",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_tags_item_id"), "item_tags", ["item_id"], unique=False
    )
    op.create_index(op.f("ix_item_tags_tag_id"), "item_tags", ["tag_id"], unique=False)
    op.drop_index(
        op.f("ix_reading_list_tags_reading_list_id"), table_name="reading_list_tags"
    )
    op.drop_index(op.f("ix_reading_list_tags_tag_id"), table_name="reading_list_tags")
    op.drop_table("reading_list_tags")
    op.drop_index(op.f("ix_reading_list_title"), table_name="reading_list")
    op.drop_index(op.f("ix_reading_list_user_id"), table_name="reading_list")
    op.drop_table("reading_list")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_list",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM("BOOK", "ARTICLE", name="kind_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("PLANNED", "READING", "DONE", name="status_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM("LOW", "NORMAL", "HIGH", name="priority_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "notes", sa.VARCHAR(length=2500), autoincrement=False, nullable=False
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('reading_list_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="reading_list_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="reading_list_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_reading_list_user_id"), "reading_list", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_reading_list_title"), "reading_list", ["title"], unique=False
    )
    op.create_table(
        "reading_list_tags",
        sa.Column("reading_list_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_list_id"],
            ["reading_list.id"],
            name=op.f("reading_list_tags_reading_list_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("reading_list_tags_tag_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reading_list_tags_pkey")),
    )
    op.create_index(
        op.f("ix_reading_list_tags_tag_id"),
        "reading_list_tags",
        ["tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_list_tags_reading_list_id"),
        "reading_list_tags",
        ["reading_list_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_item_tags_tag_id"), table_name="item_tags")
    op.drop_index(op.f("ix_item_tags_item_id"), table_name="item_tags")
    op.drop_table("item_tags")
    op.drop_index(op.f("ix_items_user_id"), table_name="items")
    op.drop_index(op.f("ix_items_title"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
